### ISSUE TITLE
Players can somehow now use color in /me?

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1374]
Im using 8.3.8 on Paper 1.12.2, I moved my server today to a new host and copied over everything exactly, so the players started stress testing to see if I missed something, and they found out they can use color in /me &cThis will be red.
None of them have any of the permissions from https://github.com/kangarko/ChatControl-Pro/wiki/Permissions#chat-formatter

I'm using LuckPerms 4.4.22.

Edit: they can also use color when they speak in bungee chat with !

is this related to #1315

**Comment by kangarko** [comment]
I believe this is solved in the latest version.

**Comment by FrozenBeard** [comment]
I updated to latest version and this did not fix it. They can still use colors in me and bungee chat

**Comment by FrozenBeard** [comment]
Why was this closed.
I have had to globally disable both my bungee chat and /me for everyone due to this bug.

**Comment by kangarko** [comment]
Thanks, I have adjusted the code to remove & letters from colors/decor players don't have access to.
