### ISSUE TITLE
[Important!] Double messages in-game, once in console

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1389]
I updated to 8.3.14 and changed the CHECKER priority to HIGHEST.

Ever since, anything a player types will be shown twice in the chat. In the console it only shows once though. The bungee chat is the default chat.

http://prntscr.com/p2zyxb

**Comment by kangarko** [comment]
I cannot reproduce sorry! Please ZIP me your CCP folder and tell me what channels are players in? Also do they have anything else enabled such as global chat ?

**Comment by Sikatsu** [comment]
After doing /chc reload it fixed for me. Still kinda odd that this occured after a restart though.

**Comment by Sikatsu** [comment]
It starts to happen after each restart. Bungee chat is enabled by default and linked to another server. It happened as of the latest update when I also changed the CHECKER priority to HIGHEST. A simple /chc reload fixes it until the next restart.

**Comment by kangarko** [comment]
We need to find out what exactly happens after a /chc reload? Can you do /channel before and after the reload? Seems like players may be getting added to a chat channel as well as the bungee mode which is not a channel and that's why the doubling occurs.

**Comment by Sikatsu** [comment]
Don't think that's it.

ChatControl // Channel functionality is disabled. Set 'Enabled' to 'true' in channels.yml to turn it on.

**Comment by Sikatsu** [comment]
It's definatly something since one of the latest updates. Might have been 8.3.14

**Comment by kangarko** [comment]
I am really having a hard time reproducing:

![a](https://i.imgur.com/BCfSDKL.png)

Can you ZIP me your ChatControl now as it is?

Oddly enough I was able to reproduce double chat when using any shortcut such as "!". I fixed that, see if that solves your issue as well.

**Comment by Sikatsu** [comment]
Hmm the update didn't fix it for me. It's really since some recent update and after I changed the CHECKER priority.

This is my ChatControl folder currently:

https://www.dropbox.com/s/bsolow9jm4orplb/ChatControl.rar?dl=0

**Comment by Sikatsu** [comment]
@kangarko Any news on this? :)

**Comment by kangarko** [comment]
Yes yes, I got some health challenges going on but I am on it! I am a single mans team so far, welcoming other developers if you know someone.

**Comment by kangarko** [comment]
Should be fixed today's evening or tomorrow early. Having a sticky note!

**Comment by Sikatsu** [comment]
Thanks, looking forward to the update and take good care of your health!

**Comment by kangarko** [comment]
SOLVED!

Thank you so much for your patience! It was a nasty issue in that your both Checker and Formatter priorities were the same, and Bukkit had put Formatter first. The formatter then sent the regular chat message first, then Checker would sent the second message from bungee chat and since you had the same format they two looked the same. Fixed!

-Matej
