### ISSUE TITLE
notify colour

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1453]
Issue with colour formatting. Defaults text to white:

`&6Hey {playername} testing 123`

what i expect to see is:
`&6Hey &e&o{playername}&6 testing 123`
but instead i see:
`&6Hey &e&o{playername}&f testing 123`

Could you add a method that fixes this. It can be achieved by getting the colour of the text before playername.

Config:
```yaml
Sound_Notify:
  Enabled: true
  Cooldown: 2 seconds
  Require_Afk: false
  Require_Prefix: 'none'
  Sound: ENTITY_EXPERIENCE_ORB_PICKUP, 100F, 1F
  Color: '&e&o'
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r
```
Chatcontrol version: 8.4.7
Paper 1.14.4 - 225

**Comment by kangarko** [comment]
Hello,

this is a known issue. Currently there is no workaround. Since the chat API splits of chat message into different parts (https://www.spigotmc.org/wiki/the-chat-component-api/), we can only see the color of the last part, which appears to be white to ChatControl. The player's color appears to be located in his prefix. 

Lastly you can try melting all format parts together to see if that makes any difference, but I am not sure: https://i.imgur.com/JNELGnw.png

**Comment by LogGits** [comment]
Couldnt a work around be to apply the colourcode at the beginning of the next string. 
`e.g. &6Hi this is a test`
would turn into:
`e.g. &6Hi &6this &6is &6a &6test`

in doing so this wouldnt impact text like:
`&6Hi this is a &atest`

As it would apply the &6 at the beginning of the &a.
You can also utilise `ChatColor.getLastColors("");` to help achieve this.

Players have been bugging me about this, and large plugins like CMI, utilise a similar type of method to achieve mentions with colour persisting.

**Comment by kangarko** [comment]
Thanks. I reviewed the code but this is already being done in a semi-similar way as you shown.

![a](https://i.imgur.com/hykKXeV.png)

How are you setting the &6 color for players? Through formatting.yml?

**Comment by LogGits** [comment]
I wish mine was like that haha. So our config looks like this:
```
Formats:
  Chat:
    Prefix:
      Message: '&r{pl_prefix}'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&8*-----* &f{player} &8*-----*'
        - '&aPrefix&8: &7{pl_prefix}'
    Player:
      Message: '{player}&f:'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&6Username: &f{player}'
        - '&7Click to send a PM'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/msg {player} '
    The_Rest:
      Message: '{pl_suffix} {message}'
```

**Comment by LogGits** [comment]
I just observed something interesting.
when testing with this:
```
test &btest {playername} test2
```
the colour of &b transfers over to test 2
if my chatcolor `{pl_suffix}` is &6 this is the result:
```
&6test &btest &e&o{playername} &btest2
```
the issue seems to be when i don't specify a colour at the beginning of the string. Something weird is happening with the {pl_suffix}.

if my chatcolour is gold and i type `test test test test test {playername} test2 test3` the text after the mention is white. However, if i explicitly type &6 at the beginning, the text after is gold.

**Comment by kangarko** [comment]
Sorry for the delay, we found something strange during the testing and we are still in the testing phase, please be patient and @lackoSK will return to you shortly, thanks.

**Comment by LogGits** [comment]
@kangarko changing your chatcolour using the /chatcolor gui removes this issue. so im assuming using what that does, will fix it.

**Comment by lackoSK** [comment]
Hello,

Thank you for adding me to an excellent point to look on. 

I'll try to review the code again and see what's wrong there and fix it ASAP.

Regards,
lackoSK

**Comment by LogGits** [comment]
@lackoSK any news on this?

**Comment by lackoSK** [comment]
Hey,

Not yet, I can **not** figure this out. It's a truly strange issue.

May take a while to be fixed. 

Be patient ;-)

Regards,
lackoSK

**Comment by LogGits** [comment]
How is it going? I am getting a lot of complaints about this. I am going to make my own workaround while i wait for you to fix this. @kangarko i'd appreciate it if you could look into this.

**Comment by kangarko** [comment]
Apology for the delay, I will take this up with my staff members.

@lackoSK

**Comment by lackoSK** [comment]
Hello,

We were working today, and we fixed it.

You can download the newest version and get the fixed ChatControl!

Big thanks to you for reporting this issue. 

Best Regards,
lackoSK

**Comment by LogGits** [comment]
Latest update doesnt fix this. Instead it removes the space after the username.

**Comment by lackoSK** [comment]
Hello,

We were working today, and we fixed it.

You will be able to download the newest version of the fixed ChatControl SOON!

Best Regards,
lackoSK

**Comment by LogGits** [comment]
Not fixed in latest version but the swear replacement is perfect. Do you have a discord id it would be easier if i could just direct msg you

**Comment by lackoSK** [comment]
Hi there, 

I'm sorry but it works just fine.
![image](https://user-images.githubusercontent.com/53174757/76242762-81492800-6237-11ea-853d-994fd4165b31.png)

Regards,
lackoSK

**Comment by LogGits** [comment]
Still an issue, was able to reproduce this on @lackoSK's test server with him. @kangarko when you're free can you please take a look into this. Im assuming it'd be an easy fix because of its nature. Lacko should be able to show you and if not, i have a zip file that i can dm you at any time that makes it reproduceable just by tagging someone using "test {playername} test2".

**Comment by kangarko** [comment]
Hi, sorry for the delays, we're working on rewriting the whole formatting ecosystem. I am teaching my team members on how to do that and coding on the side myself, it should be done in mid/late-April already and I will let you know over Discord! Thanks for your patience and apology you experienced poor customer service, Ladislav is a great guy he just needs to get more experience (I spend 9yrs doing it)

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you.

Sincerely,
Ladislav from MineAcademy.org

**Comment by LogGits** [comment]
@kangarko can you please reopen this as it still happens in version 8.7.4.

**Comment by kangarko** [comment]
Did this get fixed on 9.0.0 by the way? I remember spending a LOT of time on this, as I said the old system was broken so if the 9.0.0 got it fixed I am not going to backport it, but it will come soon again.

**Comment by LogGits** [comment]
I never tried 9.0.0 because i was well aware the plugin would be broken. But if you'd like to test, add me on discord I can run some tests on an updated version of v8 I'm currently running 8.7.9 (cant use 8.7.10 because it breaks a feature i use).

**Comment by AngellitoX** [comment]
Hello, reopening as requested.

**Comment by LogGits** [comment]
There is no "workaround".

**Comment by kangarko** [comment]
Understood. Let's do what I can and discuss it on the new ticket. However, I'll not waste days rewriting it if the new version will cover it anyways that will come in under 1 month.
