### ISSUE TITLE
You entirely broke private messages, AND created issues with coreprotect colors?

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1467]
Paper-1617 (MC: 1.12.2) 
ChatControl: 8.4.9

I updated DiscordSRV which forced me to update ChatControl which nowadays seems extremely dangerous with the untested builds being released all the time, low and behold full meltdown of the most basic thigns.

1) Now im getting thousands of messages about CoreProtect in my log after updating ChatControl pro https://gist.github.com/FrozenBeard/e6eacb760af6ebcaeda44f9b06a7a94f
2) You entirely broke private messages:

```
[22:15:59] [Server thread/INFO]: ChatControl 8.4.9 encountered a cOm2! Please check your error.log and report this issue with the information in that file.
[22:15:59] [Server thread/INFO]: org.mineacademy.chatcontrol.final.nul. .cOm2: Report / Data count != valid values count in PM_LOOKUP! Data: 4 vs 5
[22:15:59] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .lPt2.const(SourceFile:78)
[22:15:59] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:65)
[22:15:59] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:47)
[22:15:59] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .AUX.const(SourceFile:165)
[22:15:59] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:320)
[22:15:59] [Server thread/INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[22:15:59] [Server thread/INFO]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[22:15:59] [Server thread/INFO]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:15:59] [Server thread/INFO]: at java.base/java.lang.Thread.run(Thread.java:834)
[22:15:59] [Server thread/INFO]: !-----------------------------------------------------!
```

I cannot see my console from the sheer amount of spam now.

From the error.log
```
More Information: 
Data count != valid values count in PM_LOOKUP! Data: 4 vs 5
cOm2 Report / Data count != valid values count in PM_LOOKUP! Data: 4 vs 5
	 at org.mineacademy.chatcontrol.final.nul. .lPt2.const(SourceFile:78)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:65)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:47)
	 at org.mineacademy.chatcontrol.final.nul. .AUX.const(SourceFile:165)
	 at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:320)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
----------------------------------------------------------------------------------------------
```
It seems I was on 8.4.5 before I "upgraded" to 8.4.9, so something in between those to nail it down.
How can a basic routine update to 1 plugin cause so many issues? was this entirely untested?

**Comment by JavaFactoryDev** [comment]
Hey FrozenBeard,

Thanks for using ChatControl-Pro,

We will try to figure out the cause of the issue asap & fix it if possible.

Can you send us your plugins/ChatControl folder as a .zip-Folder?

Regards,
Leonhard | JavaFactory from MineAcademy

**Comment by FrozenBeard** [comment]
You should be able to figure it out knowing its only between 8.4.5 -> 8.4.9 something to do with private messaging and color!

I can send you a PM with my configs, I've spent a lot of time on my configs and don't want them public.

**Comment by lackoSK** [comment]
@FrozenBeard please send us your config to spigot https://www.spigotmc.org/members/kangarko.3321/

Thanks!

Regards,
lackoSK

**Comment by kangarko** [comment]
Hi Tom,

I apology for the trouble. I did test all changes made however the problem was I totally forgot to push the new update: https://i.imgur.com/C3V76R9.png

This is now fixed, please update your BungeeControl.

For the issue n1, I am not sure how this relates with our plugins, however I believe this will get solved after you update BungeeControl. If not, please comment below. Thank you.

**Comment by FrozenBeard** [comment]
Top man, thanks for the fast response, anything like this is super stressful for me as I have a lot of players go mental very fast! I will update BungeeControl now.

**Comment by FrozenBeard** [comment]
This did not fix the issue, updated to BungeeControl-2.2.3.jar and restarted both servers, same issues.

**Comment by kangarko** [comment]
Hi,

I apology for the continuous problems. @lackoSK @JavaFactoryDev may you please take a look soonest possible?

As promised, I finally have a great team of talented people so things will get better with faster support and higher quality updates very soon.

**Comment by FrozenBeard** [comment]
@lackoSK @JavaFactoryDev

**Comment by Kbryst** [comment]
I'm also having this exact issue.

Paper spigot 1.14.4. I just updated today from 8.4.8 (and did update bungee bridge as well)

https://pastebin.com/aK3hi91K

Let me know what information you need from me.

**Comment by Sikatsu** [comment]
Any news on this?

**Comment by kangarko** [comment]
Hi,

this is now resolved. Sorry for the delays, my team members were not able to resolve this so I did this time.

-Matej
