### ISSUE TITLE
Bug join message

### ISSUE THREAD

**Issue by AurelienGamings** [kangarko/ChatControl-Pro#1536]
Hello I have a problem with the connection messages they are hidden by the plugins I cannot find where the disconnection works

**Comment by lackoSK** [comment]
No,

They are not? 

You can find messages settings in file named **messages.yml** and you can change it here.

**Comment by AurelienGamings** [comment]
Join Message and Quit message are deactivated I use essentials but only the Quit message of essentials works when I deactivate chatcontrol it does not pose any more problem

> No,
> 
> They are not?
> 
> You can find messages settings in file named **messages.yml** and you can change it here.


Join Message and Quit message are deactivated I use essentials but only the Quit message of essentials works when I deactivate chatcontrol it does not pose any more problem

**Comment by lackoSK** [comment]
Do you have enabled them in gamerules?

**Comment by farisjaclyn** [comment]
Hello, I'm having this same issue. 

Join_Message are not working. Log out messages are.
Enabled: True
They have the permission - chatcontrol.joinmessage.staff
Stopped working in paper spigot 1.15.2 #80

**Comment by lackoSK** [comment]
Hey,

Guys, I am sorry, but I can not restimulate the issue.
![image](https://user-images.githubusercontent.com/53174757/73523030-394e0e80-440a-11ea-8853-3dd2d38c5ab9.png)

I am running only ChatControl on my server. Nothing else, nothing more.

Can you provide me some steps - how to do it? 

Regards,
lackoSK

**Comment by AurelienGamings** [comment]
Hello my problem is solved with the plugins updates

**Comment by farisjaclyn** [comment]
This isn't solved.

I deleted Chat Controls Pro and reinstalled on my 2nd server just to see if re-writing my settings would help. It isn't.
![faris](https://user-images.githubusercontent.com/46360512/73666172-f7ba9f00-4667-11ea-8771-ac9a7a57f14e.JPG)

**Comment by farisjaclyn** [comment]
The welcome message does not work and for some reason the "I joined for the 100th time" message always pops up.
