### ISSUE TITLE
Formatting Conditions not working as expected

### ISSUE THREAD

**Issue by Tina-King** [kangarko/ChatControl-Pro#1542]
**Explanation**
This stopped working on 1.15.2 version:
`Condition: '!player.hasPermission("minestar.nonplayer")'`

Right now, everyone is passing the condition meaning they get the message part.

Basically, everyone with the `minestar.nonplayer` permission should not be able to have their skyblock island level as a prefix in chat, but currently people with the permission are still getting skyblock level in chat.

**Version**
This worked fine until I updated to 1.15.2 and then got 8.5.7.

**Permissions System**
I use Luckperms permission system.

**The formatting config**
```YML 
 Chat:
    BSkyBlock_Part: 
      Message: "&7[Lvl. &3{level_bskyblock_island_level}&7] &r"
      Condition: '!player.hasPermission("minestar.nonplayer")'
```

**Comment by lackoSK** [comment]
Hello,

You have " ! " in your condition, so that means, every user who DONT have permission -> give them the island level prefix. 

Regards,
lackoSK

**Comment by Tina-King** [comment]
Thats correct, but everyone (even with the permission) gets the island level prefix.

**Comment by lackoSK** [comment]
Hello,

Well, It's because of issue #1531, we had to disable JavaScript functionality temporarily. We need to figure out the missing Nashorn part in newer Java versions. 

I hope you understand.

Regards,
lackoSK

**Comment by Tina-King** [comment]
Is there another way for me to test if someone does not have a permission?

**Comment by lackoSK** [comment]
Hi,

Not yet. It should be fixed today <)

Regards,
lackoSK

**Comment by Tina-King** [comment]
Excellent, thanks!

**Comment by Tina-King** [comment]
Just updated to 8.5.8 and it is not fixed.

**Comment by lackoSK** [comment]
Hey,

Yes, we would figure it out on our team-call (yesterday) but we couldn't. 
Please, be patient. It's a strange issue with Java.

Kind Regards,
lackoSK

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting the issue.

It is fixed in the newest version of ChatControl ^^

Regards,
lackoSK

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting the issue.

It is fixed in the newest version of ChatControl ^^

Regards,
lackoSK

**Comment by Tina-King** [comment]
@lackoSK This is not fixed, I have updated and still I have the prefix even though I have the permission `minestar.nonplayer`

**Comment by lackoSK** [comment]
#1531

**Comment by lackoSK** [comment]
Okay,

We've released version 8.6.3, which should fix this issue.

If the issue continues for you, feel free to message under it, and we will re-open it. 

PS: Thank you for reporting it ^^ 

Best,
lackoSK
