### ISSUE TITLE
bungee_server_name placeholder is returing 0

### ISSUE THREAD

**Issue by michelmans** [kangarko/ChatControl-Pro#1544]
I'm having an issue with the {bungee_server_name} placeholder.
In some servers in our network it's working fine and returning the server name, in others it's returning a 0.

Where is this value coming from? The chatcontrol config files are the same across all servers, except the Server names of course.

**Comment by lackoSK** [comment]
Hey,

I am pretty sure it's coming out of BungeeCord's config.yml
- Change it here.

Regards,
lackoSK

**Comment by michelmans** [comment]
Thanks for responding.

It's both set in the config.yml in the BungeeCord and in the BungeeControls config with the server-names setup. However it's not working.

**Comment by lackoSK** [comment]
Where are you trying to use it?

**Comment by michelmans** [comment]
I'm using it in a hover message above the chatmessage.
The chat runs on every server in the Bungee network, for example it does work for Survival and Creative, but it doesn't work for the Lobby and Skyblock.

**Comment by lackoSK** [comment]
Okay, weird, it might be caused by the JS problems in ChatControl which are fixed in the newest version.

Can you give it a try?

**Comment by michelmans** [comment]
They sadly still do not work. Somehow it works on a few and on others it doesn't. We already tried to copy the config and it's still not working.

Where is the value coming from?

**Comment by lackoSK** [comment]
Hi,

Just wait, there became some more issues with the JS.
Again, the JS may be the cause.

I hope you understand.

Regards,
lackoSK

**Comment by lackoSK** [comment]
Okay,

We've released version 8.6.3, which should fix this issue.

If the issue continues for you, feel free to message under it, and we will re-open it. 

PS: Thank you for reporting it ^^ 

Best,
lackoSK

**Comment by michelmans** [comment]
Excuse me, I was away for a while.

However the issue is still there. In some servers this is working, on others it isn't.

**Comment by lackoSK** [comment]
Zip everything and send it.
