### ISSUE TITLE
1.15.2: ChatControl 9.0.0 - Hover formatting is bolding all lines despite having no formatting codes & reset codes.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1699]
Paper dev 348 (Spigot 1.15.2)
Waterfall dev 346 (BungeeCord)
ChatControl-Pro v9.0.0
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1591793461

**bungee_chat.yml** & **chat.yml** both mirror this configuration.
```
Composition:
- Part: '&7{javascript_prefix} '
  Hover:
  - '&f&lName:&r {player}'
  - '{javascript_tag}'
  - '&e{javascript_description}'
- Part: '{display_name}&f: '
  Hover:
  - '{player}'
- Part: '{message}'
```

How it looks with v9.0.0
![link](https://i.imgur.com/U9acizE.png)

formatting.yml setup in v8.6.6
```
  Chat:
    Default:
      Message: '&7{javascript_prefix} '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&f&lName:&r {player}'
        - '{javascript_tag}'
        - '&e{javascript_description}'
      Sender_Permission: chatcontrol.groups.default
    Player:
      Message: '{display_name}&f: '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '{player}'
    The_Rest:
      Message: '{message}'
```

How it looked with v8.6.6
![link2](https://i.imgur.com/FPZIy8S.png)

**Comment by mibby** [comment]
Still an issue as of 9.0.0-BETA-3.

**Comment by lackoSK** [comment]
Hello,

This is a bit deeper issue. We will be working on it soon.

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org

**Comment by mibby** [comment]
@lackoSK This is still a problem with ChatControl 9.0.1-BETA. The &r reset codes inside javascript placeholders is not being read. ChatControl v8 does not have this issue.

![link-p](https://i.imgur.com/W9tuXUT.png)

formats/bungee_chat.yml
```
Composition:
- Part: '&7{javascript_prefix} '
  Hover:
  - '&f&lName:&r {player}'
  - '{javascript_tag}'
  - '&e{javascript_description}'
- Part: '{display_name}&f: '
  Hover:
  - '{player}'
- Part: '{message}'
```

PlaceholderAPI Javascript Variables

tag.js
```
var tags = "%deluxetags_tag%";

function hasTag()
{
  if (tags == '')
  {
    return "&b&lRank:&r &8<&7%vault_rank%&8>";
  }
   else {
       return "&b&lTag:&r %deluxetags_tag%";
   }
}

hasTag();
```

prefix.js
```
var prefix = "%deluxetags_tag%";

function hasPrefix()
{
  if (prefix == '')
  {
    return "&8<&7%vault_rank%&8>";
  }
   else {
       return "%deluxetags_tag%";
   }
}

hasPrefix();
```

description.js
```
var description = "%deluxetags_tag%";

function hasDescription()
{
  if (description == '')
  {
    return "Primary rank displayed.";
  }
   else {
       return "%deluxetags_description%";
   }
}

hasDescription();
```

**Comment by mibby** [comment]
@lackoSK @JavaFactoryDev Still an issue as of 9.0.3-BETA.

**Comment by mibby** [comment]
Still an issue as of ChatControl 9.0.4. Please re-open the ticket.
