### ISSUE TITLE
1.16.1: How spy work on chanels

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl-Pro#1895]
I have 4 channels, and want to spy on local channel, but is not auto join when i change channels. Do i have to remove auto join read channels for it work ?

**Comment by AngellitoX** [comment]
Hello there, you should be also able to achieve this by giving yourself the specific permission to read the channel even though if you are not inside of it. I'd suggest you trying that way and checking if it solves your issue.

I'm marking this as solved, consider commenting back if this didn't help you. Thank you!
Angel from MineAcademy.org

**Comment by broken1arrow** [comment]
> 
> 
> Hello there, you should be also able to achieve this by giving yourself the specific permission to read the channel even though if you are not inside of it. I'd suggest you trying that way and checking if it solves your issue.
> 
> I'm marking this as solved, consider commenting back if this didn't help you. Thank you!
> Angel from MineAcademy.org

I has put in chatcontrol.channel.autojoin.localchannel.spy

**Comment by kangarko** [comment]
Please put "Debug" option to be "[channels]" then let us know your console messages when this happens.

**Comment by broken1arrow** [comment]
> 
> 
> Please put "Debug" option to be "[channels]" then let us know your console messages when this happens.

So, i hope reload is ok, and you can mention i have to set it in settings.yml (took me little time to understand, yes not more an 60 seconds but still :P) :)
https://pastebin.com/argCSQCp

**Comment by broken1arrow** [comment]
> 
> 
> Please put "Debug" option to be "[channels]" then let us know your console messages when this happens.

So, is it a bug or i set something wrong?

**Comment by kangarko** [comment]
Hi, sorry for the delay and sorry that I forgot to tell you where to put that option! I am investigating this and will return to you in 1-2 days.

**Comment by kangarko** [comment]
Please write to me exactly what permissions you have when you change channels and the spy channel gets lost.

**Comment by broken1arrow** [comment]
chatcontrol.channel.autojoin.mc-admin.read , chatcontrol.channel.autojoin.mc-globalt.write , chatcontrol.channel.autojoin.mc-lokalt.read , chatcontrol.channel.autojoin.mc-lokalt.spy chatcontrol.channel.spy

Some perms i get from I am in "admin" group in permission plugin and some from my player rank. I have some more perms but i guess this is most imported of this (I have ofc chatcontrol.channel."cannel".join. perm too).

also for example this perms:
chatcontrol.channel.mc-lokalt.join.spy 
chatcontrol.channel.mc-lokalt.join.write
chatcontrol.channel.join.mc-globalt.join.write

**Comment by kangarko** [comment]
Thanks, I am on it, sorry it is taking a bit long, should give you more information or a fix tomorrow.

**Comment by kangarko** [comment]
Alright so I believe I have fixed the problem yesterday.

Please ensure you only have 1 autojoin permission per channel. If you still have:

- chatcontrol.channel.autojoin.mc-admin.read
- chatcontrol.channel.autojoin.mc-globalt.write
- chatcontrol.channel.autojoin.mc-lokalt.read
- chatcontrol.channel.autojoin.mc-lokalt.spy

Please remove one mc-lokalt permission to only keep one autojoin permission per channel.

**Comment by broken1arrow** [comment]
> 
> 
> Alright so I believe I have fixed the problem yesterday.
> 
> Please ensure you only have 1 autojoin permission per channel. If you still have:
> 
>     * chatcontrol.channel.autojoin.mc-admin.read
> 
>     * chatcontrol.channel.autojoin.mc-globalt.write
> 
>     * chatcontrol.channel.autojoin.mc-lokalt.read
> 
>     * chatcontrol.channel.autojoin.mc-lokalt.spy
> 
> 
> Please remove one mc-lokalt permission to only keep one autojoin permission per channel.

Yes i think perhaps be a problem, but was not sure.

chatcontrol.channel.autojoin.mc-lokalt.read
I get this perm through my player rank, so I can solve it by giving it to the players when they log in for the first time (not perfect, but can solve it that way quite simply).

**Comment by broken1arrow** [comment]
> 
> 
> Alright so I believe I have fixed the problem yesterday.
> 
> Please ensure you only have 1 autojoin permission per channel. If you still have:
> 
>     * chatcontrol.channel.autojoin.mc-admin.read
> 
>     * chatcontrol.channel.autojoin.mc-globalt.write
> 
>     * chatcontrol.channel.autojoin.mc-lokalt.read
> 
>     * chatcontrol.channel.autojoin.mc-lokalt.spy
> 
> 
> Please remove one mc-lokalt permission to only keep one autojoin permission per channel.

Is not fixed, i remove  chatcontrol.channel.autojoin.mc-lokalt.read and have left chatcontrol.channel.autojoin.mc-lokalt.spy but when i switch between channels it not set me in spy mode only read.

**Comment by kangarko** [comment]
Okay so can you please list me all permissions you have? Starting the next version you will also be able to use /chcperms command

**Comment by broken1arrow** [comment]
chatcontrol.bypass.channellimit <<<< this is false
chatcontrol.channel.autojoin.mc-globalt.write
chatcontrol.channel.autojoin.mc-✆hjälp.read
chatcontrol.channel.mc-globalt.join.write
chatcontrol.channel.mc-globalt.leave
chatcontrol.channel.mc-globalt.send
chatcontrol.channel.mc-lokalt.join.write
chatcontrol.channel.mc-lokalt.leave
chatcontrol.channel.mc-lokalt.read <<<< I have turn this off, no differences.
chatcontrol.channel.mc-lokalt.send
chatcontrol.channel.mc-✆hjälp.join.write
chatcontrol.channel.mc-✆hjälp.leave
chatcontrol.channel.mc-✆hjälp.send

perms i have some admin
chatcontrol.channel.autojoin.mc-admin.read
chatcontrol.channel.autojoin.mc-lokalt.spy
chatcontrol.channel.mc-admin
chatcontrol.channel.mc-admin.join.write
chatcontrol.channel.mc-admin.leave
chatcontrol.channel.mc-admin.send
chatcontrol.channel.mc-lokalt.join.spy
chatcontrol.channels.spy
chatcontrol.chat.spy
chatcontrol.command.adminchat
chatcontrol.command.channels.set
chatcontrol.command.channels.spy

**Comment by kangarko** [comment]
Thanks, unfortunately still I was not able to find it... Sorry for this taking too long! Can you please upload your ChatControl folder as a ZIP?

**Comment by broken1arrow** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5251416/ChatControl.zip)

Here you have it

**Comment by kangarko** [comment]
@broken1arrow thanks, I removed your comment since you also uploaded your database connection password. Please change it asap. I am going to test it right now.

**Comment by kangarko** [comment]
Awesome thank you for providing these files.

I believe I have solved the problem! Please test the next version that will be released in 30 minutes.

If you still will have any issues, please report exactly how to reproduce and I will fix those too 👍

**Comment by broken1arrow** [comment]
> 
> 
> Awesome thank you for providing these files.
> 
> I believe I have solved the problem! Please test the next version that will be released in 30 minutes.
> 
> If you still will have any issues, just report them below with steps on how exactly to reproduce them and I will fix those too +1
Try you latest version, not get it working now either. ups I miss to remove the password. 
https://youtu.be/twAqlF_FiGQ

**Comment by broken1arrow** [comment]
> 
> 
> Awesome thank you for providing these files.
> 
> I believe I have solved the problem! Please test the next version that will be released in 30 minutes.
> 
> If you still will have any issues, just report them below with steps on how exactly to reproduce them and I will fix those too +1

Ho is it going, do you need more info?

**Comment by kangarko** [comment]
Thanks, I will have a look within 24 hours, sorry for waiting!

**Comment by kangarko** [comment]
Hey, I am working on it, will keep you updated 👍

**Comment by kangarko** [comment]
@broken1arrow so sorry about the delay, so I reviewed the code and there is no such feature that would automatically place you to spy mode when you join another channel. Instead, the other channel mode is changed to "read".

I have added that option to the next version!
![a](https://i.imgur.com/bfGrpoo.png)

**Comment by broken1arrow** [comment]
> 
> 
> @broken1arrow so sorry about the delay, so I reviewed the code and there is no such feature that would automatically place you to spy mode when you join another channel. Instead, the other channel mode is changed to "read".
> 
> I have added that option to the next version!
> ![a](https://camo.githubusercontent.com/b7d5bcb61488dce9299f13f47cb375487805c2d7/68747470733a2f2f692e696d6775722e636f6d2f62664772706f6f2e706e67)

sounds really good :)

**Comment by broken1arrow** [comment]
> 
> 
> @broken1arrow so sorry about the delay, so I reviewed the code and there is no such feature that would automatically place you to spy mode when you join another channel. Instead, the other channel mode is changed to "read".
> 
> I have added that option to the next version!
> ![a](https://camo.githubusercontent.com/b7d5bcb61488dce9299f13f47cb375487805c2d7/68747470733a2f2f692e696d6775722e636f6d2f62664772706f6f2e706e67)

I try it out, and it work fine, but one problem. can you set some sort of perm on this (so normal players not get access)? 

like this you already have chatcontrol.channels.spy link it so if you have it you can spy on a channel. if it possible.

**Comment by kangarko** [comment]
Thank you I will push an update with that in a few days!
