### ISSUE TITLE
1.15.2: Ranges are acting as a global range?

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl-Pro#1973]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5256930/ChatControl.zip)

Hiya, it's me again I have set up my channels and formats but after setting the ranges of each individual chat. They don't seem to work properly they are sending global messages when I am way out of the range of the channels range.

I have disclosed my chatcontrol folder since I am unsure if I have done something wrong or if this is an error.

Here is my plugin list:
Characters
ChatControl
CMI
LuckPerms
PlaceholderAPI
ProtocolLIb
Vault

(This is on a non-production server)

**Comment by Ash10744** [comment]
I have disabled linked worlds but this error is occurring I am trying to find a solution in the closed issues but cannot seem to find a solution so I'll leave this here.

**Comment by kangarko** [comment]
I fixed that in the next version but you will need only to use one Range option and remove the other one like this:

![a](https://i.imgur.com/EXEsY2s.png)

**Comment by Ash10744** [comment]
Alright thank you!

**Comment by Ash10744** [comment]
Hi I updated to the latest version it's still occurring:

I attached my new zip for chatcontrol to see if I did anything wrong

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5278679/ChatControl.zip)

**Comment by kangarko** [comment]
Please ensure you or your players don't have any of these two permissions:

![a](https://i.imgur.com/h3YHTFb.png)

**Comment by Ash10744** [comment]
Yeah they do not have any of those perms specified.

**Comment by Ash10744** [comment]
Nevermind I am stupid it was the bypass world permission I am sorry 
thank you for the help though!

**Comment by Ash10744** [comment]
Closing this but thank you for the support and aid regarding this ! 👍
