### ISSUE TITLE
[7.6.x] DiscordSRV Issues

### ISSUE THREAD

**Issue by le0-minelandeu** [kangarko/ChatControl-Pro#378]
Hi, it looks like your plugin doesn't work with DiscordSRV. I have reconfigurated whole ChatControlPro (took almost 5 hours) so there is no doubt that mistake is on my side. It would be nice if you asked the developer of DiscordSRV and fixed this issue. I am not the only one (@osimer is my friend from same server), there are many people in the Discussion that are asking if this works. 

Also, the Discord hook was the main reason why I bought your plugin. So if you don't want to provide support for DiscordSRV it would be nice to remove this "feature" from your mainpage of ChatControlPro or change it to BROKEN (but removing would be better). I don't want to threaten you (really not, I just want to be fair with other users of Spigot Forums), but If you won't make any decision I will have to inform the staff of Spigot Forums to solve this because now you are doing fake advertising for premium plugin which I personally thing isn't fair.

When we add soft-depend: chatcontrol to DiscordSRV, we managed it to work, specific message from specific channel was sent to discord but not other way. Maybe this is some way to solve it? 

P.S.: also, I thing this way of solving this issue is much better than crying in the review section (if you understand me :) )

**Comment by kangarko** [comment]
Hey,

I understand it is frustrating when things do not work. Yes I noticed other users' reports as well, but I could not determine what their issue is because I lack enough information.

From my testing, all works correctly:
![a](https://i.imgur.com/KdNj90Q.png)

What exactly is your issue?

**Comment by jiribanka** [comment]
this means you are Czech, which is awesome, so we can use our mother language because I am Czech too. I will give you my configs and formating-

I haven't tried using this feature with chats, I used it with channels. I want to have messages from channels like support hooked to discord chats #support but not to the main discord chat which I wanted to hook to global chat - but not the /chc global since I am using the channels only. It is getting really confusing, should I write in Czech or you want the description in English so others can solve it too? 😄 

In basic, I don't want to use any global or bungee chats that are configurated by default. I want to have channels only. I need separated chat for #support and #at, also for #global (like global chat). Every channel I want to have bungeecord: true. In game, everything works fine _(apart from the wierd /ch send feature which don't work correctly when player (admin in our case) is in multiple chats (write, read, read, read etc.) and he just want to send one message to other channel but the plugin doesn't allow it, he has to leave all chats and then join them again in read, write, read combination))_.

But when I am hooking the specified channels to the specified discord, it just wont work. Everything is sent to #global chat by default and then it is transmitted to other channels like #support or #at. This means that the basic hook with Discord somehow works, but it doesn't work in our case - hooking specified channels to specific discord channels). We now have to decide if we want to use VentureChat (which I must say sucks but hooks specified channels to specified discord channels) and provide support through Discord or Telegram (we have another hook) or we want to use your ChatControl and belive that you will solve this issue. 

In this log, the DiscordSRV is loaded after ChatControlPro, I can give you older one when are both ChatControlPro and DiscordSRV loaded on startup.

Jestli by to nevadilo, preferoval bych v příště češtinu (lépe to půjde vysvětlit) 😄 (in a case you are really Czech)

Also, I want to apologize for the end of @osimer conversation, he was getting pretty upset and so he wrote the "We are switching to VentureChat" thing 😅 
[ChatControl+log.zip](https://github.com/kangarko/ChatControl-Pro/files/1324698/ChatControl.log.zip)

**Comment by kangarko** [comment]
Hey,

I am Slovak :) But feel free to continue in English so people can understand us.

Please try the new version and set Compatibility.Cancel_Event to true in channels.yml.

Also, make sure you have linked your channels properly via DiscordSRV's config.yml. Below is an example of linking the three default ChatControl's channels (make sure you have them created first on the Discord server)

> Channels: {"standard": "360681175129391119", "admin": "360690730152493056", "global": "360690714650214401"}

**Comment by jiribanka** [comment]
I am really sorry but I cant understand how to set Compability.Cancel_Event to true? Is is in the settings or channels.yml (generated in new version)? I can't find it on the wiki.

**Comment by malonnnn** [comment]
@jiribanka 

Check this out, this is my channels.yml:
https://www.hastebin.com/oyugawenec.bash

You'll notice the very last line is Cancel_Event under the Compatibility node. Set it to true. If you do not see this choice, ensure that you are using version 7.5.7 of Chat Control Pro, as this was a recent addition added today.

**Comment by jiribanka** [comment]
[Screenshots.zip](https://github.com/kangarko/ChatControl-Pro/files/1325912/Screenshots.zip)

This should provide you informations you want. Channel hook from ingame chat to discord chat works fine. But when player writes from any channel from discord (I mean from any hooked channel), It is sent to default channel (which is in this case "global" channel).

Also, please keep in mind that it would be awesome if we could somehow display or not display prefixes (ex. in global chat display, in support chat is no need for that since in support you know who is admin) 
Ex.:
(Both Messages sent from Discord)

[AT] _Le0_ > message (we don't use [Global] prefix because it is useless in this case (no local chats))
[Support] _Le0_ > message (no need for [Support] [AT] _Le0_ > message)

This is little sidenote but it would be nice if it was in there (Venture Chat doesn't have that feature and i really don't like it - you have to have one style for all chats which I think is horrible) - it is last screenshot, it should be possible (defining something like {pl_prefix} but for discord {discord_prefix} or whatever.). It is little extra improvement and it will give to ChatControl another awesome feature.

Example screenshot how this "works": 
![screenshot 2017-09-22 23 35 26](https://user-images.githubusercontent.com/31539367/30765305-5211dc06-9fef-11e7-920f-d321a7eb2c71.png)

**Comment by malonnnn** [comment]
@jiribanka 

Please post your configs for DiscordSRV and ChatControl (settings, messages, formatting). You can use hastebin.com

**Comment by osimer** [comment]
@malonnnn I am owner of the same server, so here are our configs of DiscordSRV:

https://gist.github.com/anonymous/f7e8327881668a96be18bb748db4c93a

**Comment by jiribanka** [comment]
The config file is fine, it worked with VentureChat.

**Comment by malonnnn** [comment]
@kangarko -  I need a little help with this one, their configs look generally okay to me.

**Comment by osimer** [comment]
The thing that is interesting is, that if we load server with VentureChat - DiscordSRV report "hooked with VentureChat" ... but when we load server with ChatControl Pro - DiscrodSRV report something like "no hooks found" ... 

If you guys want to see it live on our server, we could show you...

**Comment by malonnnn** [comment]
@jiribanka @osimer 

I don't know if this is really gonna be super helpful, but DiscordSRV put out two updates yesterday (https://www.spigotmc.org/resources/discordsrv.18494/updates). Hopefully that might help.

But in the meantime, while we wait for Kangargo, could one of you maybe post a full server startup log? Those can be very useful.

**Comment by osimer** [comment]
@malonnnn I updated DiscordSRV, but it didn't help. However, here is a full server startup log:
https://pastebin.com/14bLNPFa

**Comment by kangarko** [comment]
Hey @jiribanka  @osimer @malonnnn !

I have looked at the code and the current way Discord was handled, was only **one way**. Any incoming message was left for DiscordSRV to handle, thus ending at the global chat, always.

In the next version, I have worked on adding it so Discord's messages are sent to their respective channel, if not configured otherwise. There are lots of new options so I highly suggest you open ChatControl.JAR and look at channels.yml file with the commentaries to understand how it works.

Lastly, the "No chat found" message from Discord is because Discord has special hooks for plugins itself, and obviously ChatControl is not inside because it is a premium resource. Don't worry it will still work.

Thank you for your patience & please let me know if you have any more issues!

Ďakujem :) 
Prajem pekný deň

**Comment by jiribanka** [comment]
Thank you so much. I will configure it tommorow.

**Comment by osimer** [comment]
@kangarko  super! Díky moc!

**Comment by jiribanka** [comment]
@kangarko Okey, the hook is fine now. But the messages from Discord to Channel are duplicated. I have two servers and bungeecord. I also have CancelEvent: true as you said last time.

But now take your time off, we will wait.

**Comment by jiribanka** [comment]
Hi, I hope you enjoyed your free time. I was working on finding new issues in the latest versions.
All screens, configuration, errors and server start log are included in attached file.

**1.) Doublemessaging with DiscordSRV**
In this case i might found the mistake. Due to bad configuration on our servers (one is using UTC 0 time zome and second is using CEST +2) you can clearly see that messages from DiscordSRV are handled via bungeecord _(screen1.1,1.2,1.3)_, because they are send to both channels which are with bungeecord:true in channel settings. Also, I must say that we cannot have DiscordSRV on one server only, this option wouldn't been able to send messages from server that hasn't got DiscordSRV to Discord channel. Also, we have hooked consoles (DiscordSRV feature) to our Discord. In console there is only one message sent. When player is offline, the duplication isn't happening.

After some new tests we discovered that doubling is happening when players aren't on the same server _(screens included - screen1.5,1.6,1.7,1.8)_ This is breaking even more when we use /chc reload, more duplication is happening _(screen1.9,1.10 and so on)_

**2.) DiscordSRV format when player is in game**
This is quite impressive feature but we are using different chat formats for different groups. Ex.: when you click on [AT] prefix, it will suggest you command /helpop, with hovering on VIP you will see where he bought it and what is the benefits etc... But when message is sent from Discord it will use all options for prefix that it has. _(viz screen2.1,2.2)_

**3.) MySQL issues**
The database isn't working properly. We have db adress in configs right, but when we join, weird error is in the console _(error1)_ I am including full server startup and all my config files. Also, .db file has some data in it, but we have mysql: true.
[ChatControlIss.zip](https://github.com/kangarko/ChatControl-Pro/files/1357082/ChatControlIss.zip)


That being said are the bugs i found in recent version.

**Comment by jiribanka** [comment]
None of these issues were solved in update 7.5.12. I'am still waiting for the answer.

**Comment by kangarko** [comment]
Hey, I am on it, please mind 1-2 days before a full fix.

**Comment by kangarko** [comment]
Hello,

I apology for the late reply.

**1) Doublemessaging**
This issue has been completely resolved. 

**2) DiscordSRV format when player is in game**
I have been unable to directly resolve the issue, so I have added a new option Apply_Natural_Format_If_Online to channels.yml, that, if disabled, won't format the chat and only print out the standard [Discord] format even if the same player is on both Discord and the MC server.

**3) MySQL issues**
This error has been resolved.

Thank you once again for waiting and for putting the time and effort into packaging all into the single zip file, it has made the process of fixing much more faster and convenient.

PS: A new version will be available within a few hours. 

PPS: Please let me know if any other issues arise (it will get fixed sooner this time).

Sincerely,
kangarko

**Comment by le0-minelandeu** [comment]
**1) Doublemessaging**
In basic, everything works fine. But after /chc reload, the doublemessaging keeps happening again. /stop will fix this issue. But in normal conditions it works fine.
![screenshot 2017-10-12 17 13 18](https://user-images.githubusercontent.com/31539367/31503956-561857d0-af71-11e7-83ce-9e3a49f8c221.png)


**2) DiscordSRV format when player is ingame**
Wasn't fixed for me, still can see all prefixes even with the new option.
![screenshot 2017-10-12 17 04 03](https://user-images.githubusercontent.com/31539367/31504495-d1d0dc7a-af72-11e7-8c23-7fbad279d0d5.png)

**3) MySQL issue**
Fixed. Thank you for that.

I love the new update, it isn't working in some ways but it is still better than drátem do oka. 😄

**Comment by kangarko** [comment]
I have fixed the double-messaging issue.

For the Discord prefix issue, please make sure you have **Apply_Natural_Format_If_Online** to false in channels.yml.

**Comment by le0-minelandeu** [comment]
**1.)**
I am sorry to say that but it wasn't fixed. It still keeps happening when i use /chc reload.

**2.)**
Apply_Natural_Format_If_Online = false

I have that. It looks like it doesn't do anything. I am using permission based prefixes (You have that VIP prefix in default settings). Every group has permission chat.* set to false (it is my custom permission) and their group is set to true (ex. chat.at true). If I use both prefixes (chat.vip and chat.at both on true) I will have two prefixes ([VIP] and [AT]). When the message is send from Discord to game (to global chat), it will use all formats - it ignores permissions. That is why it creates these long prefixes. Sorry for late responding I was quite busy with other things.

New ChatControlPro settings:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/1385457/ChatControl.zip)

**Comment by kangarko** [comment]
Hey, I have worked on the both issues, and they appear to be fixed from my testing. I am leaving this open however, in case you find it otherwise.

Please test against a new release.

**Comment by le0-minelandeu** [comment]
None of these issues wasn't fixed. Is there anything to update in config files? I am using 7.6.2.

**Comment by kangarko** [comment]
No db cleaning needed.

Is the duplication coming from Discord?

**Comment by kangarko** [comment]
Drobnosť: Všimol som si z vašeho posledného ChatControl.zip, že po pripojení dostanem hlášku aby som sa pripojil do global čatu, ktorý avšak neexistuje. Farba hlášky sa mi zdá nekonzistentná na konci.

![img](https://i.imgur.com/VV7062u.png)

**Comment by le0-minelandeu** [comment]
Tato hláška se nezobrazuje po připojení na náš server, default skupina (hráči) mají permicii na autojoin do kanálu hra. Global chat jsem měl nastaven nejprve, pak jsem synchronizoval název s kanálem na discordu #hra, protože jsem si myslel, že proto to buguje a už to tak zůstalo. 

Nyní zkouším odebrat v nastavení DiscordSRV %toprole% pro všechny zprávy z DiscordSRV.

**Comment by le0-minelandeu** [comment]
To nepomohlo, vypadá to, že je stále chyba v ChatControlu (DiscordSRV) by teď měl přeposílat pouze nicky z Discordu, není tomu tak, stále tam jsou prefixy.

**Comment by kangarko** [comment]
Práve som vydal novú verziu, testoval som na privátnom Diskord serveri, malo by to byť v poriadku + formátovanie sa zobrazí podľa povolení.

**Comment by kangarko** [comment]
P.S: Keď nahrávate ChatControl.zip, prosím odstráňte MySQL sekciu nech sa vám nikto nenapojí do databázy. Ak je problém vyriešený radím odstrániť vaše predchádzajúce príspevky.

**Comment by le0-minelandeu** [comment]
Velice děkuji za vyřešení obou problémů, /chc reload neduplikuje zprávy a zprávy z Discordu nemají tisíce prefixů. Obdivuji kvalitu podpory, sám bych ztratil nervy. Tento problém je vyřešen, kdyby se přece něco stalo, otevřu novou issue. Jdu napsat 5* hodnocení na Spigot, protože za těch pár dolarů tohle rozhodně stojí.

**Comment by kangarko** [comment]
Ďakujem krásne a cením si to :)
