### ISSUE TITLE
Private Messages Malfunctions on Bungee

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#627]
Awesome update dude!

But i wanne make a report about chc color or chc c after choosing the color the menu does close. Maybe something that was forgotten?

Edit: Color is not applying when using a plugin such as deluxechat (Would like to see support for deluxechat)

**Comment by AmazedMender16** [comment]
Another issue i have found is:

  # Prevent from private messaging yourself?
  Deny_Message_Self: true

This still allows players to PM themselfs. Trief both ways with false and true still allowing players to PM themselfs

**Comment by kangarko** [comment]
Hey, the menu won't close, this is a feature. I don't plan on adding support for DeluxeChat sorry.

The PM issue was fixed :)

**Comment by AmazedMender16** [comment]
This issue is still present! 
When trying to message AmazedLady i get a message you cannot message yourself. Which is impossible since my name is AmazedMender16 📃

**Comment by AmazedMender16** [comment]
When
Private_Messages:
  Enabled: true
  Bungee: false

Bungee is set to TRUE messages are not sending. not even to players on the same server no console errors/no chat output

**Comment by LogGits** [comment]
@kangarko #556 would be a better implementation. Keep the ignoring of capitals and ignoring different forms of the character but remove the percentage system. Just loop through all players and find the first one that contains the argument. This same principle can be used to add messaging to players with nicknames/custom display names.

**Comment by kangarko** [comment]
Hey, sorry for the delay, we already use a mixture of the implementation you suggested.

I just tested on 7.8.2, the PM's are being sent properly over Bungee. Make sure you connected through Bungee and not directly to the Bukkit server, so Bungeecords can register you.

I also tested the inability of sending messages to self, this has been patched I believe in 7.8.1-2, please re-test.

**Comment by AmazedMender16** [comment]
Weird that i havent been able to send a message over bungee then. Im directly connected over the bungee. The server didnt even respond with a message that the message was send to the player

**Comment by kangarko** [comment]
I just updated BungeeControlBridge. Try disabling partial matching completely.

**Comment by AmazedMender16** [comment]
Currently having the issue, that on one server you can send a player a message on the other server but not the other way around?

**Comment by kangarko** [comment]
What are the player names specifically?

**Comment by AmazedMender16** [comment]
Wickd1g and merkaah

**Comment by AmazedMender16** [comment]
After 2 restarts it started working, quite weird in my eyes.

**Comment by kangarko** [comment]
Let me know when it stops working. Also when

**Comment by AmazedMender16** [comment]
Im again trying to send a message to a user on a different server now fully updated to 7.8.2 and bridge 2.1 and it again is not showing a message of the message being send. 

About chc color. plugins like chatcolor+ do work with deluxechat. I have no clue. I would like to use the ability to use the chatcolor that comes with chc

**Comment by AmazedMender16** [comment]
When trying to send a message on the same server the other user is in it doesnt work either with bungee enabled. When bungee is disabled it works fine

**Comment by AmazedMender16** [comment]
Chatcolor+ works fine with deluxechat that was what im trying to say :P Would love to see the chatcontrol one working with it aswel ;/

Ill see the debug messages

**Comment by AmazedMender16** [comment]
Not seeing any debug messages showing up..
[25.03.2018 12:28:06] [CMD] AmazedMender16: /msg _Tristan test
[25.03.2018 12:28:41] [CMD] AmazedMender16: /msg _Tristan hello there

**Comment by kangarko** [comment]
Those debug messages are in the next version ;)

Have you tried editing the listener priority?

**Comment by AmazedMender16** [comment]
Yeah i have tried editing the listener priority do i need to enable formatting? in the formatting.yml? 
Cuzz if i enable it it overwrites my deluxechat config

Editing the listener priority didnt work

**Comment by kangarko** [comment]
Well no if you have DeluxeChat. Listener priority of Formatter is for formatting.yml which must be enabled. It won't do anything if it's disabled.

**Comment by AmazedMender16** [comment]
Debug message when trying to send to a player on the same server
Sending bungee message [CHATCONTROL, PM_LOOKUP]: AmazedMender16, _Tristan, d, {"extra":[{"extra":[{"extra":[{"color":"white","text":"Server "},{"color":"dark_gray","text":"// "},{"color":"green","text":"You have received a message from AmazedMender16"},{"color":"dark_gray","text":": "},{"color":"white","text":"d"}],"clickEvent":{"action":"suggest_command","value":"/r "},"hoverEvent":{"action":"show_text","value":[{"text":"Private Message\nReceived 25.03.2018 13:32:45\nSender: AmazedMender16\n\nClick for a reply."}]},"text":""}],"text":""}],"text":""}, 

This when sending over to another server
Sending bungee message [CHATCONTROL, PM_LOOKUP]: AmazedMender16, _Tristan, d, {"extra":[{"extra":[{"color":"white","text":"Server "},{"color":"dark_gray","text":"// "},{"color":"green","text":"You have received a message from AmazedMender16"},{"color":"dark_gray","text":": "},{"color":"white","text":"d"}],"clickEvent":{"action":"suggest_command","value":"/r "},"hoverEvent":{"action":"show_text","value":[{"text":"Private Message\nReceived 25.03.2018 13:34:28\nSender: AmazedMender16\n\nClick for a reply."}]},"text":""}],"text":""}, 

Note: Messages are not sending no output in the chat either

**Comment by AmazedMender16** [comment]
Somehow version 7.8.4 does work with deluxechat nice!

**Comment by kangarko** [comment]
I am on it, it may take a while due to other work.

**Comment by AmazedMender16** [comment]
Awesome! keep chc color the way it is now :P it works with deluxechat!

**Comment by kangarko** [comment]
Confirmed. Working on a fix right now.

**Comment by kangarko** [comment]
Surprisingly this turned out to be rather caused by Essentials (from my testing).

I added Ignore.Report_To_Essentials option to the next version. Please disable it and test whether you will be still able to reproduce this bug. 

Thank you for your patience.

**Comment by AmazedMender16** [comment]
Tho i have removed the entire ignoring command from essentails :D idk if this helps or not. I will test it out

**Comment by AmazedMender16** [comment]
This ignoreing issue broke my entire server... half of the players cant see eachother messages! insane! Hope u can come with a fix! tried clearing the databases and all..... BTW 7.8.10 is broken and crashing servers

**Comment by AmazedMender16** [comment]
Ignore issues is still present..... Hope u will have a fix for it very soon. I even disabled ignore command on essentions side. Private messages are done by chatcontrol pro.

**Comment by kangarko** [comment]
@AmazedMender16 sorry for getting late back to you, I am in the middle of a videocourse so I cannot guarantee full support in June unfortunately

Anyways, I've done extensive testing with channels and private messages using MySQL and having the two players on a different servers, but I could not reproduce:
![a](https://i.imgur.com/jA8pApz.png)

What I need from you is the exact steps on how you use ChatControl so I can reproduce it and finally fix it:
- Example, do you have channels or formatter enabled?
- Are players on the same/different server?
- etc..

The very best would be if you could ZIP me your ChatControl/ folders from two servers between which it occurs, so I can install this to my environment and test it out. Make sure to remove MySQL passwords information. 

Thanks.
kangarko

**Comment by AmazedMender16** [comment]
I will test cross server later. For now ignoring is still bugged out like hell. People unignore players after a long time and they still arent able to see people their messages.

**Comment by AmazedMender16** [comment]
Sorry,

I have send the files of chatcontrol and essentials over on spigot!

**Comment by kangarko** [comment]
So far I cannot reproduce, I am sorry for that, will continue testing.

I see now you that you have Formatter and Channels disabled, and that the chat is not linked in your bungee network using ChatControl. What other plugin are you using that formats the chat?

The /ignore command is mainly used for ChatControl's formatter and channels.

Do you use MySQL Integration? I see it being on false but data redacted.

Here is your Essentials version with their /ignore command removed from their plugin.yml, test it out whether you spot any changes.
[EssentialsX.zip](https://github.com/kangarko/ChatControl-Pro/files/2110694/EssentialsX.zip)

**Comment by AmazedMender16** [comment]
Haha, 

The files i use have them removed already.. and yes i disabled mysql for testing.

Im using deluxechat for the chat.

**Comment by kangarko** [comment]
Is it possible to disable DeluxeChat for 1 day to see if the /ignore issue persist?

**Comment by AmazedMender16** [comment]
Hello,

This is sadly no possibility for me..

**Comment by kangarko** [comment]
@AmazedMender16 great find! I have opened an issue on Essentials tracker (https://github.com/EssentialsX/Essentials/issues/2064)

For now, please test using the "Report_To_Essentials" option on false in your settings.yml.

**Comment by AmazedMender16** [comment]
Then nothing is being written in the essentials files. But i think this is why my entire ignoring is f*cked up...

![screenshot_4](https://user-images.githubusercontent.com/14223424/42125123-e2258e7e-7c70-11e8-92b4-10c287918a53.png)

**Comment by kangarko** [comment]
@md678685 thank you for the help!

I edited my code in ChatControl and so it should prevent this situation from happening. Here's the relevant part: 
![a](https://i.imgur.com/2hhmEFc.png)

May I ask when are you planning to add the check to Essentials?

Thanks,
Matej

**Comment by kangarko** [comment]
Closing, for further assistance or support please comment below.

**Comment by AmazedMender16** [comment]
What version includes this fix?

**Comment by kangarko** [comment]
Not sure about Essentials, but latest ChatControl and latest BungeeControlBridge have the changes.

**Comment by AmazedMender16** [comment]
Allright will test it out.. Will update both essentials and chatcontrol/bridge
