### ISSUE TITLE
Bungee Messages Name Confusion

### ISSUE THREAD

**Issue by sgort87** [kangarko/ChatControl-Pro#708]
When both players are on the same server, it handles right, but there's confusion across Bungee servers in the case of player names "Gort" and "GortBabyMama" (and surely similar cases). I have the following settings (and tried alternate settings):

pm-partial-match: 1.0   (Bungee)
Deny_Message_Self: true   (Spigot)

**Conditions and results:**
**-** PM sent across servers from "Gort" to "GortBabyMama" will send both the "Sent" and "Received" messages to "GortBabyMama", and nothing to "Gort".
**-** PM sent across servers from "GortBabyMama" to "Gort" cancels the message and reports that "GortBabyMama" cannot sent a message to themself.
**-** PM sent across servers from any other player to "Gort" will send the message to "GortBabyMama".

Edit: From some servers to others, it works correctly. It seems there's a loop that it follows and messes up if it finds "GortBabyMama" in the list first while searching for "Gort".

**Comment by sgort87** [comment]
The same thing happens when trying to enter conversation mode (on the same server) when sending a conversation start from "Gort" to GortBabyMama", but not the other way around.

Also, suggestion: for conversation mode fail when Deny_Message_Self: true, it should cancel the request instead of requiring "exit".

**Comment by kangarko** [comment]
Hello,

please set pm-partial-match to 0.0 to disable partial matching, that should fix the inconsistencies. The loop may cause unexpected problems due to the way we find player names partially. I have no control over the order. Generally, the "gort" will match "XXgortYY" according to the stricness of the partial matching. This is purely for convenience and can be disabled.

Thank you for suggesting conversation mode for bungee.

I am closing this, thanks for posting a detailed report. Please let me know below if you have more questions.

**Comment by sgort87** [comment]
Unfortunately, disabling the partial match did not fix the issue. I still have the same exact problem.

**Comment by kangarko** [comment]
Sorry for not replying in time, I re-open this and will get back to you!
