### ISSUE TITLE
[7.8.10] Double messages on bungee channels

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#719]
Since now i created a secondary hub, i used chatcontrol for create a unique channel between these two hub, and i noticed often when somesone talk i see it doubled, same if i use /chc announce, in some case, i see the broadcast two times (the issue was pretty old with the admin channel and never fixed) but here i see it more evidency
![7b375a55-4495-48eb-8eca-bf49439f7828](https://user-images.githubusercontent.com/3611852/39590371-fe0fe03c-4f00-11e8-9089-154bdf32b537.jpg)
![57402bb3-f03a-47f3-8676-5deb70beb0cb](https://user-images.githubusercontent.com/3611852/39590387-0832f5e0-4f01-11e8-8d46-9473c5e8edd9.jpg)

**Comment by kangarko** [comment]
Hello xion,

I apology for a late reply, please post me your settings.yml and channels.yml.

Also, can you test whether it is doubled when you have 2 players on the server from where the message comes, and even tripled when there are 3 players, and so on?

**Comment by xion87** [comment]
I attached the requested files here
[data.zip](https://github.com/kangarko/ChatControl-Pro/files/1988343/data.zip)

**Comment by kangarko** [comment]
Thank you.

**Comment by xion87** [comment]
Now with 7.8.11, on hub sometimes i see the leave message of player (is a server where i disabled join/leave message)
![image](https://user-images.githubusercontent.com/3611852/39913135-1c96d37a-5501-11e8-8049-6c35b8689a80.png)
On console it spam errors about playerquit event: https://pastebin.com/xMhfrbWA

**Comment by kangarko** [comment]
@xion87 does it happen all the time or only after server has started?

It seems to me that the error starts in the messages like "Processing login for X took 1680ms", so everything is delayed and then when the player is trying to log in but quits in the middle of the process, ChatControl still gets the "quit event" notification from Bukkit but an error is produced instead. I would rather advise to write on spigotmc forums because honestly I don't have much experience with this plugin combination and automatic log-ins.

**Comment by xion87** [comment]
1) The leave error happen only with 7.8.12, is not present with lower version (i think you touched something about it). On hub i have the setting **Hide_Join_Quit_Kick_Messages: true** 
2) The double messages happens only with bungee channels (admin and hub channels)

**Comment by kangarko** [comment]
@xion87 sorry for forgetting to reply, I have actually tested both issues quite some time ago and believe they should be fixed. Did you experience any of these recently?

**Comment by xion87** [comment]
the bug is still present in 7.8.22 (only on channels) i think it happen if you write in exact time with something else...

**Comment by kangarko** [comment]
Just testing, cannot track it down so far.

How exactly can I reproduce the problem?

Finally, are you only joined in one channel or more?

**Comment by kangarko** [comment]
@xion87 I will be unable to access my workspace for 2 weeks now, if you provide the data until then I will come back and fix it afterwards

**Comment by kangarko** [comment]
BungeeControlBridge got a major update covering issues with PM's. I assume it fixed this issue as well.

Make sure to wait for the incoming ChatControl 7.8.30 to test it out.

**Comment by xion87** [comment]
the bug is still present in 7.9.4 version
